<?$APPLICATION->IncludeComponent("altop_old:catalog.top", "discount_left",
	Array(
		"DISPLAY_IMG_WIDTH" => "200",
		"DISPLAY_IMG_HEIGHT" => "200",
		"SHARPEN" => "30",
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "3",
		"ELEMENT_SORT_FIELD" => "rand",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_FIELD2" => "",
		"ELEMENT_SORT_ORDER2" => "",
		"SECTION_URL" => "",
		"DETAIL_URL" => "",
		"BASKET_URL" => "/personal/cart/",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"DISPLAY_COMPARE" => "Y",
		"ELEMENT_COUNT" => "3",
		"LINE_ELEMENT_COUNT" => "",
		"PROPERTY_CODE" => array("NEWPRODUCT", "SALELEADER", "DISCOUNT", "MANUFACTURER"),
		"FLAG_PROPERTY_CODE" => "DISCOUNT",
		"OFFERS_LIMIT" => "",
		"PRICE_CODE" => array(
			0 => $_SESSION["VREGIONS_REGION"]["PRICE"],
		),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_PROPERTIES" => array(),
		"USE_PRODUCT_QUANTITY" => "Y",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "86400",
		"CACHE_NOTES" => "",
		"CACHE_GROUPS" => "N",
		"HIDE_NOT_AVAILABLE" => "N",
		"CONVERT_CURRENCY" => "N",
		"CURRENCY_ID" => ""
	),
	false
);?>