<?$APPLICATION->IncludeComponent(
	"bitrix:catalog.bigdata.products", 
	".default", 
	array(
		"COMPONENT_TEMPLATE" => ".default",
		"RCM_TYPE" => "any",
		"ID" => "",
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "3",
		"SHOW_FROM_SECTION" => "N",
		"SECTION_ID" => "",
		"SECTION_CODE" => "",
		"SECTION_ELEMENT_ID" => "",
		"SECTION_ELEMENT_CODE" => "",
		"DEPTH" => "",
		"HIDE_NOT_AVAILABLE" => "N",
		"SHOW_DISCOUNT_PERCENT" => "N",
		"PRODUCT_SUBSCRIPTION" => "N",
		"SHOW_NAME" => "N",
		"SHOW_IMAGE" => "N",
		"MESS_BTN_BUY" => "Купить",
		"MESS_BTN_DETAIL" => "Подробнее",
		"MESS_BTN_SUBSCRIBE" => "Подписаться",
		"PAGE_ELEMENT_COUNT" => "8",
		"DETAIL_URL" => "",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "36000000",
		"CACHE_GROUPS" => "Y",
		"DISPLAY_IMG_WIDTH" => "178",
		"DISPLAY_IMG_HEIGHT" => "178",
		"SHARPEN" => "30",
		"DISPLAY_COMPARE" => "Y",
		"SHOW_POPUP" => "Y",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"SHOW_OLD_PRICE" => "N",
		"PRICE_CODE" => array(
			0 => $_SESSION["VREGIONS_REGION"]["PRICE"], //0 => "Интернет-магазин (oblikdom.ru)",
		),
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"CONVERT_CURRENCY" => "Y",
		"BASKET_URL" => "/personal/cart/",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"PRODUCT_QUANTITY_VARIABLE" => "",
		"ADD_PROPERTIES_TO_BASKET" => "Y",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"USE_PRODUCT_QUANTITY" => "N",
		"SHOW_PRODUCTS_3" => "Y",
		"PROPERTY_CODE_3" => array(
			0 => "",
			1 => "",
		),
		"PROPERTY_CODE_MOD" => array(
			0 => "GUARANTEE",
		),
		"CART_PROPERTIES_3" => array(
			0 => "",
			1 => "",
		),
		"ADDITIONAL_PICT_PROP_3" => "BACKGROUND_IMAGE",
		"LABEL_PROP_3" => "-",
		"PROPERTY_CODE_#OFFERS_IBLOCK_ID#" => array(
			0 => "COLOR",
			1 => "PROP2",
			2 => "PROP3",
		),
		"CART_PROPERTIES_#OFFERS_IBLOCK_ID#" => array(
			0 => "COLOR",
			1 => "PROP2",
			2 => "PROP3",
		),
		"ADDITIONAL_PICT_PROP_#OFFERS_IBLOCK_ID#" => "",
		"OFFER_TREE_PROPS_#OFFERS_IBLOCK_ID#" => array(
			0 => "COLOR",
			1 => "PROP2",
			2 => "PROP3",
		),
		"CURRENCY_ID" => "RUB",
		"PROPERTY_CODE_4" => array(
			0 => "",
			1 => "",
		),
		"CART_PROPERTIES_4" => array(
			0 => "",
			1 => "",
		),
		"ADDITIONAL_PICT_PROP_4" => "MORE_PHOTO",
		"OFFER_TREE_PROPS_4" => array(
		),
		"SHOW_PRODUCTS_34" => "N",
		"PROPERTY_CODE_34" => array(
		),
		"CART_PROPERTIES_34" => array(
		),
		"ADDITIONAL_PICT_PROP_34" => "",
		"LABEL_PROP_34" => "",
		"SHOW_PRODUCTS_43" => "N",
		"PROPERTY_CODE_43" => array(
		),
		"CART_PROPERTIES_43" => array(
		),
		"ADDITIONAL_PICT_PROP_43" => "",
		"LABEL_PROP_43" => "",
		"SHOW_PRODUCTS_45" => "N",
		"PROPERTY_CODE_45" => array(
		),
		"CART_PROPERTIES_45" => array(
		),
		"ADDITIONAL_PICT_PROP_45" => "",
		"LABEL_PROP_45" => ""
	),
	false
);?>